# spring:
#   application:
#     name: study
#   config:
#     import: "configserver:"
#   cloud:
#     config:
#       uri: http://localhost:8888

spring:
  # cloud:
  #     config:
  #       enabled: false   # tắt config server
  # eureka:
  #   client:
  #     enabled: false      # tắt Eureka client
  application:
    name: study

  datasource:
    url: jdbc:postgresql://192.168.0.148:5432/ktpm_study # todo change db name
    username: khoidev # todo change username
    password: khoicktv # todo change password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # none | validate | update | create | create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 8081

# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:8761/eureka/
#   instance:
#     hostname: localhost
#     preferIpAddress: false
#     instanceId: ${spring.application.name}:${server.port}

logging:
  file:
    name: path # todo change log file name
