# spring:
#   application:
#     name: submit
#   config:
#     import: "configserver:"
#   cloud:
#     config:
#       uri: http://localhost:8888

spring:
  application:
    name: submit

  data:
    mongodb:
      uri: mongodb://admin:khoicktv@192.168.0.148:27017/?authSource=admin
      host: 192.168.0.148
      port: 27017
      database: ktpm_submit

server:
  port: 8082

# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:8761/eureka/
#   instance:
#     hostname: localhost
#     preferIpAddress: false
#     instanceId: ${spring.application.name}:${server.port}

logging:
  file:
    name: /home/khoitrananh/Documents/hcmut/hk251/co3017/be-assignment/log/submit-log-20251202.log
